# Generated by Django 4.2.6 on 2023-11-24 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
    ]
